name: Multiple Unity Test Example

on: push

jobs:
  runAllTestsOnUnity2019:
    name: Run tests for version ${{ matrix.unityVersion }} 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.38f1
          - 2020.3.37f1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-
          restore-keys: |
            Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -profile SomeProfile -someBoolean -someValue exampleValue
#  runAllTests:
#    name: Run tests for version ${{ matrix.unityVersion }}
#    runs-on: ubuntu-latest
#    timeout-minutes: 15
#    strategy:
#      fail-fast: false
#      matrix:
#        projectPath:
#          - test-project
#        testMode: [ playmode, editmode ]
#        unityVersion:
#          - 2019.4.38f1
#          - 2020.3.37f1
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#        with:
#          lfs: true
#      - name: Cache Project
#        uses: actions/cache@v2
#        with:
#          path: ${{ matrix.projectPath }}/Library
#          key: Library-${{ matrix.projectPath }}
#          restore-keys: |
#            Library-${{ matrix.projectPath }}
#            Library-
#      - name: Run Tests
#        uses: game-ci/unity-test-runner@v2
#        env:
#          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#        with:
#          unityVersion: ${{ matrix.unityVersion }}
#          testMode: ${{ matrix.testMode }}
#          projectPath: ${{ matrix.projectPath }}
#          checkName: ${{ matrix.testMode }} Test Results
#          githubToken: ${{ secrets.GITHUB_TOKEN }}
#          coverageOptions: "generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*"
#
